const a = {
  code: 1,
  msg: '23123',
  data: {
    pageList: [
      {
        auditNumber: 1234,
        productCommonName: '哈哈哈',
        approvalNumber: 11,
        productSpecif: '22*1ml',
        price: 100,
        preferentialLimit: 5,
        preferentialPrice: 4,
        preferentialQuantity: 123,
        auditStatus: 1,
        updateTime: '2020-04-03 12:30:26',
        link: 'www.baidu.com',
      },
      {
        auditNumber: 1234,
        productCommonName: '哈哈哈',
        approvalNumber: 11,
        productSpecif: '22*1ml',
        price: 100,
        preferentialLimit: 5,
        preferentialPrice: 4,
        preferentialQuantity: 123,
        auditStatus: 2,
        updateTime: '2020-04-03 12:30:26',
        link: 'www.baidu.com',
      },
      {
        auditNumber: 1234,
        productCommonName: '诶诶饿',
        approvalNumber: 11,
        productSpecif: '22*1ml',
        price: 100,
        preferentialLimit: 5,
        preferentialPrice: 4,
        preferentialQuantity: 123,
        auditStatus: 3,
        updateTime: '2020-04-03 12:30:26',
        link: 'www.baidu.com',
      },
    ],
    pageNumber: 0,
    pageSize: 10,
    totalElements: 20,
    totalPages: 2,
  },
};
