export default {
  productImage: '商品图',
  productBrand: '商品品牌',
  productCommonName: '通用名',
  isMp: '是否处方药',
  approvalNumber: '批准文号',
  productSpecif: '包装规格',
  productExpire: '有效期',
  productType: '商品类别',
  productDesc: '商品简介',
  manufacturer: '生产企业',
  productModel: '剂型／型号',
  englishName: '英文名',
  pinyin: '汉语拼音',
  productSpec: '说明书',
};
